name: Daily Bot Trigger

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Llamar bot en Render
        run: |
          curl --silent https://trading-bot-web.onrender.com/analizar?activos=BTC-USD,ETH-USD,AAPL,TSLA
