name: Daily Bot Trigger

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Análisis Grupo 1
        run: |
          curl --silent "https://trading-bot-web-7ooa.onrender.com/analizar?activos=BTC-USD,ETH-USD,SOL-USD,AAPL,TSLA"
      - name: Análisis Grupo 2
        run: |
          curl --silent "https://trading-bot-web-7ooa.onrender.com/analizar?activos=NVDA,QQQ,ARKK,GLD,MSTR,PLTR"
