name: Escuchar comandos Telegram

on:
  schedule:
    - cron: "*/5 * * * *" # Cada 5 minutos
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar listener
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          python telegram_bot.py
